### ISSUE TITLE
Cross build for scala 2.12.x

### ISSUE THREAD

**Issue by gregghz** [lucidsoftware/relate#40]
Current 2.12.x is 2.12.0-M5.

Waiting on these projects to publish a suitable version:
- [x] https://github.com/scalameter/scalameter
- [x] https://github.com/playframework/anorm

**Comment by ruslanasa** [comment]
+1 need 2.12 relate too

**Comment by gregghz** [comment]
fixed by https://github.com/lucidsoftware/relate/pull/41
